// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWFLx7g7wksoDdKnGbNLykpPHB02olIyE',
    appId: '1:834634231354:web:8655b430f5c6071c368f03',
    messagingSenderId: '834634231354',
    projectId: 'rpm-bitdoglab',
    authDomain: 'rpm-bitdoglab.firebaseapp.com',
    databaseURL: 'https://rpm-bitdoglab-default-rtdb.firebaseio.com',
    storageBucket: 'rpm-bitdoglab.firebasestorage.app',
    measurementId: 'G-JWLM1GKMKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYzfBw6K7hlsWSMXNfcF0_jTkt09f_tR4',
    appId: '1:834634231354:android:1c0314f188100f49368f03',
    messagingSenderId: '834634231354',
    projectId: 'rpm-bitdoglab',
    databaseURL: 'https://rpm-bitdoglab-default-rtdb.firebaseio.com',
    storageBucket: 'rpm-bitdoglab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf5c9pMPw-bTYxcxCr0uz0W3qNHChImYM',
    appId: '1:834634231354:ios:80589c58430b9808368f03',
    messagingSenderId: '834634231354',
    projectId: 'rpm-bitdoglab',
    databaseURL: 'https://rpm-bitdoglab-default-rtdb.firebaseio.com',
    storageBucket: 'rpm-bitdoglab.firebasestorage.app',
    iosBundleId: 'com.appgranja.appGranja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf5c9pMPw-bTYxcxCr0uz0W3qNHChImYM',
    appId: '1:834634231354:ios:80589c58430b9808368f03',
    messagingSenderId: '834634231354',
    projectId: 'rpm-bitdoglab',
    databaseURL: 'https://rpm-bitdoglab-default-rtdb.firebaseio.com',
    storageBucket: 'rpm-bitdoglab.firebasestorage.app',
    iosBundleId: 'com.appgranja.appGranja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWFLx7g7wksoDdKnGbNLykpPHB02olIyE',
    appId: '1:834634231354:web:aff448c75954bb65368f03',
    messagingSenderId: '834634231354',
    projectId: 'rpm-bitdoglab',
    authDomain: 'rpm-bitdoglab.firebaseapp.com',
    databaseURL: 'https://rpm-bitdoglab-default-rtdb.firebaseio.com',
    storageBucket: 'rpm-bitdoglab.firebasestorage.app',
    measurementId: 'G-DWEET2GXEV',
  );
}
